/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klj.ride;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import klj.display.register;

/**
 *
 * @author meuni
 */
public class tLaTPula extends javax.swing.JFrame {

    /**
     * Creates new form tLaTPula
     */
    public tLaTPula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        seniorticketfield = new javax.swing.JTextField();
        regularticketfield = new javax.swing.JTextField();
        childticketfield = new javax.swing.JTextField();
        ticketsBookSpace = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 102, 51));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tLATPuLA.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 40, 200, 200);

        seniorticketfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                seniorticketfieldFocusLost(evt);
            }
        });
        seniorticketfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorticketfieldActionPerformed(evt);
            }
        });
        getContentPane().add(seniorticketfield);
        seniorticketfield.setBounds(390, 160, 50, 30);

        regularticketfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                regularticketfieldFocusLost(evt);
            }
        });
        regularticketfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularticketfieldActionPerformed(evt);
            }
        });
        getContentPane().add(regularticketfield);
        regularticketfield.setBounds(390, 110, 50, 30);

        childticketfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                childticketfieldFocusLost(evt);
            }
        });
        childticketfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childticketfieldActionPerformed(evt);
            }
        });
        getContentPane().add(childticketfield);
        childticketfield.setBounds(390, 60, 50, 30);

        ticketsBookSpace.setBackground(new java.awt.Color(0, 255, 204));
        ticketsBookSpace.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ticketsBookSpace.setForeground(new java.awt.Color(255, 255, 0));
        ticketsBookSpace.setText("Book");
        ticketsBookSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketsBookSpaceMouseClicked(evt);
            }
        });
        getContentPane().add(ticketsBookSpace);
        ticketsBookSpace.setBounds(460, 310, 72, 23);

        label1.setBackground(new java.awt.Color(255, 102, 51));
        label1.setText("Child Tickets");
        getContentPane().add(label1);
        label1.setBounds(300, 60, 90, 30);

        label2.setBackground(new java.awt.Color(255, 102, 51));
        label2.setText("Senior Tickets");
        getContentPane().add(label2);
        label2.setBounds(300, 160, 90, 30);

        label3.setBackground(new java.awt.Color(255, 102, 51));
        label3.setText("Regular Tickets");
        getContentPane().add(label3);
        label3.setBounds(300, 110, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundRides.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 360);

        setBounds(725, 150, 582, 369);
    }// </editor-fold>//GEN-END:initComponents

    private void childticketfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childticketfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childticketfieldActionPerformed

    private void regularticketfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularticketfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regularticketfieldActionPerformed

    private void seniorticketfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorticketfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seniorticketfieldActionPerformed

    private void childticketfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_childticketfieldFocusLost
        childticketString = childticketfield.getText();
        childticket = Integer.parseInt(childticketString);
    }//GEN-LAST:event_childticketfieldFocusLost

    private void regularticketfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regularticketfieldFocusLost
        regularticketString = regularticketfield.getText();
        regularticket = Integer.parseInt(regularticketString);
    }//GEN-LAST:event_regularticketfieldFocusLost

    private void seniorticketfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seniorticketfieldFocusLost
        seniorticketString = seniorticketfield.getText();
        seniorticket = Integer.parseInt(seniorticketString);
    }//GEN-LAST:event_seniorticketfieldFocusLost

    private void ticketsBookSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketsBookSpaceMouseClicked
        String url="jdbc:mysql://localhost:8889/KLJ?zeroDateTimeBehavior=CONVERT_TO_NULL";
        // Database credentials
        
        Connection con;
        try {
            con = DriverManager.getConnection(url,"root","root");
            PreparedStatement stmt2 = con.prepareStatement("INSERT INTO klj.ticket (ticket_regular, tiket_child, ticket_senior, ride)  VALUES (?, ?, ?, ?)");

        stmt2.setInt(1,regularticket);
        stmt2.setInt(2,childticket);
        stmt2.setInt(3,seniorticket);
        stmt2.setInt(4,ride);
        
        stmt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_ticketsBookSpaceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tLaTPula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tLaTPula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tLaTPula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tLaTPula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tLaTPula().setVisible(true);
            }
        });
    }
    int ride = 1;
    String regularticketString ;
    int regularticket;
    String seniorticketString ;
    int seniorticket;
    String childticketString ;
    int childticket;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField childticketfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField regularticketfield;
    private javax.swing.JTextField seniorticketfield;
    private javax.swing.JButton ticketsBookSpace;
    // End of variables declaration//GEN-END:variables
}
